### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### cgiffard/node-simplecrawler now has a Chat Room on Gitter

@cgiffard has just created a chat room. You can visit it here: [https://gitter.im/cgiffard/node-simplecrawler](https://gitter.im/cgiffard/node-simplecrawler?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/cgiffard/node-simplecrawler?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by cgiffard** [comment]
FWIW I was just mucking around with gitter for now. It may or may not be worth announcing that there's yet another way to badger the core team with questions already answered in the readme. ;)

**Comment by fredrikekelund** [comment]
I haven't used Gitter previously. I'm not sure I'd hang out there much, would almost rather see people report issues TBH, just because it's easier to keep track of everything in one place. But Gitter could maybe be a good place for more informal discussions

**Comment by cgiffard** [comment]
I'm really not sure. I'll have to check chat client support. If it's going to be a pain to check, it'll just frustrate people.

**Comment by fredrikekelund** [comment]
What do you think about this one, @cgiffard? I think I'd honestly prefer if we didn't have a Gitter channel, I'm fine with keeping discussions here or via email, we could start an email list if we ever feel it's necessary

**Comment by cgiffard** [comment]
Cool, I think we're not big enough to justify it at this point (it's just another place to have to look for issues.) Closing. :)

**Pull request closed without merging**
