### PR TITLE
JSHint cleanup

### PR DESCRIPTION
**Pull request by XhmikosR**
Please tell me with anything you want changed so that we get this sorted.

BTW, since the time I made the patches, I have personally switched to ESLint. I guess we can make the jump later.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Oh, and @cgiffard don't forget to pass `?w=1` in a patch's URL to see the diff without comparing whitespace.

**Comment by cgiffard** [comment]
Yeah, a lot of diffs are unreadable without that. :)

Thanks again.

**Comment by cgiffard** [comment]
Looks good! :)

**Comment by XhmikosR** [comment]
BTW I can try splitting some of the patches into separate pull requests to
speed up the review process.

**Comment by cgiffard** [comment]
It's fine for now — I already reviewed the changes a little while back, and there wasn't much difference this time around. Next time I'd definitely prefer much smaller diffs if possible.

BTW I've added you as a collaborator, so hopefully in future you're not waiting around for my approval if I'm on holiday or something!

**Comment by XhmikosR** [comment]
Cool, thanks!

I'll try to make a couple new PRs for a few things I have in mind.

**Pull request merged**
