### PR TITLE
Crawler#respectRobotsTxt now also looks for nofollow robots meta tags

### PR DESCRIPTION
**Pull request by fredrikekelund**
### What this PR changes
If the default Crawler#discoverResources method finds a <meta name="robots" value="nofollow"> tag, it will return an empty array.

### Rationale
See #278

### CODE REVIEW

**Comment by fredrikekelund** [comment]
@cgiffard I've updated the 1.0.0 release note draft to include this change. I think we're good to go with the release now :shipit: I'll go ahead and publish tomorrow unless you have any objections?

**Comment by cgiffard** [comment]
@fredrikekelund Sounds good! :)

**Comment by fredrikekelund** [comment]
@cgiffard hehe well if you respond that promptly, then I'll go ahead and release straight away!

**Comment by fredrikekelund** [comment]
Aaand done! :beers: :dancer:

**Comment by cgiffard** [comment]
@fredrikekelund Awwwwww yeah. :) Thanks!

I've got a free weekend coming up (finally!) so I'm hoping to get the CLI polished up, and maybe start on a github pages thing, where we can also stuff our generated docs. :)

**Comment by fredrikekelund** [comment]
Ah, nice to hear! :) Would be awesome if we could intertwine the API docs with some more descriptive text content (like we have in the README right now).

I've always found Sequelize's docs to be great, and they do just that - auto-generate docs that contain more than just the global classes. I think they use the mkdocs and dox modules. Seems they have a bit of a custom setup to glue everything together, but it's good inspiration in any case

**Comment by cgiffard** [comment]
That would be good to look at. I'm thinking we can probably inline usage examples too.

**Comment by fredrikekelund** [comment]
I think we should definitely aim for that! Descriptive text and usage examples in more or less the same place as the raw API documentation. As for Sequelize, https://github.com/sequelize/sequelize is the repo, and http://docs.sequelizejs.com/en/v3/ is the docs site

**Pull request merged**
