### PR TITLE
Normalize package.json.

### PR DESCRIPTION
**Pull request by XhmikosR**
* specify the files to install (lib folder)
* specify node.js 0.10 as the minimum version since that's what it's being tested
* minor properties reordering

### CODE REVIEW

**Comment by cgiffard** [comment]
Good catch. After I've reviewed all your submissions I'll bump the version and republish. :)

**Comment by cgiffard** [comment]
This kinda stuff just accrues in any project more than a few years old... :-/

**Comment by XhmikosR** [comment]
True, but things have been like that for a long time now :)

**Comment by cgiffard** [comment]
I've pretty much neglected this project for a year, haha. I'm returning to the helm to bring things back on track just today. :P

**Pull request merged**
