### PR TITLE
Added robots.txt parser example

### PR DESCRIPTION
**Pull request by fredrikekelund**
By popular demand (#153) , I added an example to show how to integrate simplecrawler with robots-parser, a module that can parse robots.txt files and query URL's against the rules in them.

### CODE REVIEW

**Comment by fredrikekelund** [comment]
I'll add some documentation to the README as well before merging this.

**Comment by cgiffard** [comment]
Cool. Looks good at first glance! :)

**Comment by fredrikekelund** [comment]
@cgiffard you think this is ready for merging?

**Comment by cgiffard** [comment]
Go for it! We now just need to make sure that this new method is documented. You hit the button. :)

**Comment by cgiffard** [comment]
Gak, got confused between this PR and the other one. Ignore my comment about documentation. ;)

**Comment by fredrikekelund** [comment]
Haha got me a bit confused at first!

**Pull request merged**
