### PR TITLE
Always match cookies with a wild card domain

### PR DESCRIPTION
**Pull request by intron**
Cookies instantiated without a domain get their domain property set
to "*" by default, which seems to imply that they should match any
domain, but matchDomain() did not treat them as such.

* Change matchDomain() to return true for cookies with domain of "*"

### CODE REVIEW

**Comment by intron** [comment]
Am I misunderstanding how this should work, or is that the expected functionality?

**Comment by fredrikekelund** [comment]
Hi, thanks for the PR!

I don't actually think cookies can be domain-less, or have a wildcard domain field?

**Comment by intron** [comment]
I don't think that's part of the standard, but Cookie() will set the domain property to * if one isn't provided, so I assumed the intention was to match everything. As it currently stands, matchDomain() tries to match "*" and returns false. Even though I wouldn't want my browser doing this, I can see why it might be helpful for testing things.

**Comment by fredrikekelund** [comment]
Ah, silly me - I see now! In that case, this looks great :+1: If you could fix the lint error and maybe squash the 2nd commit so it only results in a single one, we can go ahead and merge this!

**Pull request closed without merging**
